name: recruitment_excercise_vidmizer
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas
  - numpy
  - pytorch-cpu
  - torchvision
  - tensorflow
  # - tensorflow-gpu
  - nibabel
  - matplotlib
  - pytest
  - pillow
